game:
  grid_width: 16
  grid_height: 16
  speed: 10
  nes_mode: false
  auto_advance: false

ai:
  enable_tracing: false
  model_path: "snake_dqn_model_auto.pth"

learning:
  learning_rate: 0.001
  batch_size: 32
  episodes: 1000
  epsilon: 1.0
  epsilon_min: 0.1
  epsilon_decay: 0.995
  memory_size: 10000
  gamma: 0.95
  # FOOD-FOCUSED reward system - make food the primary objective
  food_reward: 100.0
  death_penalty: -50.0
  move_penalty: 0.001
  survival_bonus: 0.1
  distance_reward_weight: 2.0
  distance_penalty_weight: 0.1
  efficiency_bonus: 10.0
  starvation_penalty: -0.01
  starvation_threshold: 100  # Moves without food before starving (hunger meter)
  # Advanced strategy rewards
  path_efficiency_bonus: 5.0
  space_utilization_bonus: 0.5
  risk_reward_ratio: 0.3
  # Minimal oscillation prevention (don't interfere with food seeking)
  oscillation_penalty: 0.1
  direction_reversal_penalty: 0.2
  # Auto-save settings
  auto_save_enabled: true
  auto_save_interval: 1
  auto_save_filename: "snake_dqn_model_auto.pth"

display:
  screen_width: 1680
  screen_height: 720
  stats_area_height: 250
  grid_padding: 0
  panel_padding: 0
  leaderboard_file: "leaderboard.json" 